"use client";

import { useState } from "react";
import { Card, Avatar, StarRating, Badge, Button, SectionHeader, Container } from "@/components/ui";
import type { Review } from "@/lib/types/feedback";

// Mock reviews data
const reviewsData: Review[] = [
  {
    id: "1",
    name: "Alex Rivera",
    rating: 5,
    comment: "Absolutely love this tool! The architecture breakdown helped me understand a complex microservices repo in minutes instead of hours. The tech stack detection is spot-on.",
    date: "2024-01-15",
    helpful: 24,
    category: "feature",
  },
  {
    id: "2",
    name: "Jordan Smith",
    rating: 5,
    comment: "RepoRadar is now part of my daily workflow. I use it to evaluate open source libraries before adding them to our projects. The security considerations section is particularly valuable.",
    date: "2024-01-12",
    helpful: 18,
    category: "general",
  },
  {
    id: "3",
    name: "Taylor Chen",
    rating: 4,
    comment: "Great tool overall. Would love to see support for private repositories in the future. The current analysis for public repos is comprehensive and well-structured.",
    date: "2024-01-10",
    helpful: 12,
    category: "feature",
  },
  {
    id: "4",
    name: "Morgan Lee",
    rating: 5,
    comment: "The setup instructions generated by RepoRadar are incredibly helpful for onboarding new team members. It's like having a senior dev explain the codebase.",
    date: "2024-01-08",
    helpful: 31,
    category: "praise",
  },
  {
    id: "5",
    name: "Casey Brown",
    rating: 4,
    comment: "Very useful for quick code reviews. The performance insights have helped us identify bottlenecks we didn't know existed. UI is clean and intuitive.",
    date: "2024-01-05",
    helpful: 8,
    category: "general",
  },
  {
    id: "6",
    name: "Riley Park",
    rating: 5,
    comment: "As an open source maintainer, this helps me understand contributor PRs faster. The repository structure analysis is my favorite feature.",
    date: "2024-01-03",
    helpful: 15,
    category: "praise",
  },
];

type SortOption = "newest" | "highest" | "lowest" | "helpful";
type FilterOption = "all" | "5" | "4" | "3" | "2" | "1";

export function ReviewsList() {
  const [sortBy, setSortBy] = useState<SortOption>("newest");
  const [filterBy, setFilterBy] = useState<FilterOption>("all");
  const [helpfulReviews, setHelpfulReviews] = useState<Set<string>>(new Set());

  const handleHelpful = (reviewId: string) => {
    setHelpfulReviews((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(reviewId)) {
        newSet.delete(reviewId);
      } else {
        newSet.add(reviewId);
      }
      return newSet;
    });
  };

  const filteredReviews = reviewsData.filter((review) => {
    if (filterBy === "all") return true;
    return review.rating === parseInt(filterBy);
  });

  const sortedReviews = [...filteredReviews].sort((a, b) => {
    switch (sortBy) {
      case "newest":
        return new Date(b.date).getTime() - new Date(a.date).getTime();
      case "highest":
        return b.rating - a.rating;
      case "lowest":
        return a.rating - b.rating;
      case "helpful":
        return b.helpful - a.helpful;
      default:
        return 0;
    }
  });

  const getCategoryBadge = (category: string) => {
    const variants: Record<string, "default" | "success" | "warning" | "error" | "info"> = {
      feature: "info",
      bug: "error",
      general: "default",
      praise: "success",
    };
    return variants[category] || "default";
  };

  return (
    <section className="py-16 bg-slate-50">
      <Container size="lg">
        <SectionHeader
          title="User Reviews"
          subtitle="See what developers are saying about RepoRadar"
          centered
        />

        {/* Filters and Sort */}
        <div className="flex flex-col sm:flex-row justify-between gap-4 mb-8">
          {/* Filter by Rating */}
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-sm font-medium text-slate-700">Filter:</span>
            {["all", "5", "4", "3", "2", "1"].map((rating) => (
              <button
                key={rating}
                onClick={() => setFilterBy(rating as FilterOption)}
                className={`px-3 py-1 rounded-full text-sm font-medium transition-colors ${
                  filterBy === rating
                    ? "bg-slate-900 text-white"
                    : "bg-white text-slate-600 hover:bg-slate-100 border border-slate-200"
                }`}
              >
                {rating === "all" ? "All" : `${rating}★`}
              </button>
            ))}
          </div>

          {/* Sort */}
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium text-slate-700">Sort by:</span>
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as SortOption)}
              className="px-3 py-1.5 rounded-lg border border-slate-200 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-slate-500"
            >
              <option value="newest">Newest</option>
              <option value="highest">Highest Rated</option>
              <option value="lowest">Lowest Rated</option>
              <option value="helpful">Most Helpful</option>
            </select>
          </div>
        </div>

        {/* Reviews Grid */}
        <div className="grid md:grid-cols-2 gap-6">
          {sortedReviews.map((review) => (
            <Card key={review.id} className="flex flex-col">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-3">
                  <Avatar alt={review.name} size="md" />
                  <div>
                    <h4 className="font-semibold text-slate-900">{review.name}</h4>
                    <p className="text-xs text-slate-500">
                      {new Date(review.date).toLocaleDateString("en-US", {
                        year: "numeric",
                        month: "short",
                        day: "numeric",
                      })}
                    </p>
                  </div>
                </div>
                {review.category && (
                  <Badge variant={getCategoryBadge(review.category)}>
                    {review.category}
                  </Badge>
                )}
              </div>

              <div className="mb-3">
                <StarRating rating={review.rating} size="sm" />
              </div>

              <p className="text-slate-700 mb-4 flex-grow">{review.comment}</p>

              <div className="flex items-center justify-between pt-4 border-t border-slate-100">
                <button
                  onClick={() => handleHelpful(review.id)}
                  className={`flex items-center gap-1.5 text-sm transition-colors ${
                    helpfulReviews.has(review.id)
                      ? "text-slate-900 font-medium"
                      : "text-slate-500 hover:text-slate-700"
                  }`}
                >
                  <svg
                    className="w-4 h-4"
                    fill={helpfulReviews.has(review.id) ? "currentColor" : "none"}
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5"
                    />
                  </svg>
                  Helpful ({review.helpful + (helpfulReviews.has(review.id) ? 1 : 0)})
                </button>

                <button className="text-sm text-slate-500 hover:text-slate-700 transition-colors">
                  Report
                </button>
              </div>
            </Card>
          ))}
        </div>

        {/* Load More */}
        <div className="text-center mt-8">
          <Button variant="outline">Load More Reviews</Button>
        </div>
      </Container>
    </section>
  );
}
