import { NextRequest, NextResponse } from "next/server";
import { writeFile, readFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import path from "path";

const DATA_DIR = path.join(process.cwd(), "data");
const REVIEWS_FILE = path.join(DATA_DIR, "reviews.json");

async function ensureDataDir() {
  if (!existsSync(DATA_DIR)) {
    await mkdir(DATA_DIR, { recursive: true });
  }
}

async function readReviewsData() {
  try {
    const data = await readFile(REVIEWS_FILE, "utf-8");
    return JSON.parse(data);
  } catch {
    return [
      {
        id: "1",
        name: "Alex Rivera",
        rating: 5,
        comment: "Absolutely love this tool! The architecture breakdown helped me understand a complex microservices repo in minutes instead of hours.",
        date: "2024-01-15",
        helpful: 24,
        category: "feature",
      },
      {
        id: "2",
        name: "Jordan Smith",
        rating: 5,
        comment: "RepoRadar is now part of my daily workflow. I use it to evaluate open source libraries before adding them to our projects.",
        date: "2024-01-12",
        helpful: 18,
        category: "general",
      },
      {
        id: "3",
        name: "Taylor Chen",
        rating: 4,
        comment: "Great tool overall. Would love to see support for private repositories in the future.",
        date: "2024-01-10",
        helpful: 12,
        category: "feature",
      },
      {
        id: "4",
        name: "Morgan Lee",
        rating: 5,
        comment: "The setup instructions generated by RepoRadar are incredibly helpful for onboarding new team members.",
        date: "2024-01-08",
        helpful: 31,
        category: "praise",
      },
      {
        id: "5",
        name: "Casey Brown",
        rating: 4,
        comment: "Very useful for quick code reviews. The performance insights have helped us identify bottlenecks.",
        date: "2024-01-05",
        helpful: 8,
        category: "general",
      },
      {
        id: "6",
        name: "Riley Park",
        rating: 5,
        comment: "As an open source maintainer, this helps me understand contributor PRs faster.",
        date: "2024-01-03",
        helpful: 15,
        category: "praise",
      },
    ];
  }
}

async function writeReviewsData(data: unknown[]) {
  await ensureDataDir();
  await writeFile(REVIEWS_FILE, JSON.stringify(data, null, 2));
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const sortBy = searchParams.get("sortBy") || "newest";
  const filterBy = searchParams.get("filterBy") || "all";
  
  let reviews = await readReviewsData();
  
  // Filter by rating
  if (filterBy !== "all") {
    const rating = parseInt(filterBy);
    reviews = reviews.filter((r: { rating: number }) => r.rating === rating);
  }
  
  // Sort
  reviews.sort((a: { date: string; rating: number; helpful: number }, b: { date: string; rating: number; helpful: number }) => {
    switch (sortBy) {
      case "newest":
        return new Date(b.date).getTime() - new Date(a.date).getTime();
      case "highest":
        return b.rating - a.rating;
      case "lowest":
        return a.rating - b.rating;
      case "helpful":
        return b.helpful - a.helpful;
      default:
        return 0;
    }
  });
  
  return NextResponse.json(reviews);
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { name, rating, comment, category } = body;

    if (!name || !rating || !comment) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    if (rating < 1 || rating > 5) {
      return NextResponse.json(
        { error: "Rating must be between 1 and 5" },
        { status: 400 }
      );
    }

    const reviews = await readReviewsData();
    
    const newReview = {
      id: Date.now().toString(),
      name,
      rating,
      comment,
      category: category || "general",
      date: new Date().toISOString().split("T")[0],
      helpful: 0,
    };

    reviews.unshift(newReview);
    await writeReviewsData(reviews);

    return NextResponse.json({ success: true, review: newReview }, { status: 201 });
  } catch (error) {
    console.error("Error saving review:", error);
    return NextResponse.json(
      { error: "Failed to save review" },
      { status: 500 }
    );
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, helpful } = body;

    const reviews = await readReviewsData();
    const review = reviews.find((r: { id: string }) => r.id === id);
    
    if (!review) {
      return NextResponse.json(
        { error: "Review not found" },
        { status: 404 }
      );
    }

    review.helpful += helpful ? 1 : -1;
    await writeReviewsData(reviews);

    return NextResponse.json({ success: true, review });
  } catch (error) {
    console.error("Error updating review:", error);
    return NextResponse.json(
      { error: "Failed to update review" },
      { status: 500 }
    );
  }
}
